### ISSUE TITLE
Problem Statement 

### ISSUE THREAD

**Issue by whitere123** [whitere123/CAS741_REW#1]
This is the problem statement.

**Comment by smiths** [comment]
Please address the minor comments give in commit 59b466a.

**Comment by whitere123** [comment]
I do not understand your first comment. Are you referring to text width or the column width in the table?

**Comment by smiths** [comment]
Text width.  If you look at the tex files in my repo, they are typically under 80 characters wide.  This is like you are writing tex as you would write a programming language.  That way, when there is a change you will see which line has changed.

**Comment by whitere123** [comment]
Alright, I have made all of the recommended changes to the problem statement.

**Comment by smiths** [comment]
I've reviewed your edits and approve your problem statement.  I did make a few additional changes.  You can see them by looking at: b1db17c

In the future, please cite your commit number (hash) when addressing an issue.  It is easier for me (and other users) to click on the commit number than it is to manually track it down.
