### ISSUE TITLE
[SRS Review] Typos and Minor Comments about Document Formatting

### ISSUE THREAD

**Issue by hananezlitni** [whitere123/CAS741_REW#10]
**Typos:**

- **Section 2.4/Mathematical notation, line 7:** “then” instead of “than”

- **Section 3.1/Purpose of Document, line 3:** “compatible” instead of “compatibile”. Also, I believe “compatible with” is better than "compatible for”

- **Section 4.1/User Responsibilities, point 2:** Missing period "."

- **Section 5.1.3/Goal Statements, line 2:** “initial” instead of “intial”

- **Section 6.2/Nonfunctional requirements, NFR2:** “serviceable” instead of “servicable” and “physicist” instead of “physcists”  

- **Section 8/Traceability, page 13 line 1 (in the PDF file):** "dependent on the component” instead of “dependent on by the component”

**Comments about document formatting:**

- The references at the end of the document should start in a new page

- In the cover page, the first letter of each of the words in the title of the document should be capitalized

- There are some inconsistencies in the white spaces between the text and tables in some sections in the document. Examples: the gap between the text and the table in "Table of Units", no gap between the text and the "IM1" table, big gaps in the "Traceability Matrices and Graphs" section

**Comment about captions and cross-references:**

- I noticed that the cross-references and some captions were written manually. This is not an "issue" but in some cases it is better to use tex commands, such as "\iref{}" for referencing IMs. This would make the reference clickable, so the reader can jump to an IM, DD, or any other component instead of scrolling. Also, if you add/remove an IM for example, the IM number would automatically be updated because you used the command and you wouldn't have to modify the number manually. 

- The same case is for the figure/table captions. The caption in the "System Context" figure says "Diagram 1" when it should be "Figure 1", and the ones in the traceability graphs say "Figure 1/2" when it should be "Figure 2/3. 

 <br>

This is my last post (:

**Comment by whitere123** [comment]
Thank you for your feedback. This was a very thorough review!

**Comment by whitere123** [comment]
I addressed most of this issue. I will close the issue once I clean up all the spacing.

**Comment by hananezlitni** [comment]
@whitere123 you're welcome.. you also did a good job with the SRS (:
