### ISSUE TITLE
Reliability vs Serviceability 

### ISSUE THREAD

**Issue by whitere123** [whitere123/CAS741_REW#11]
Hello Dr. Smith (@smiths ), 

I just have a simple question regarding the distinction between reliability vs serviceability. 

On the internet is defines serviceability as: fit for use, helpful and useful. 

It defines reliable as : consistently good in quality and/or performance. 

On my SRS I was more concerned (at least I thought I was) with serviceability. My supervisor and I aren't too concerned with high quality or exact eigen values in our spectrum. This is a precursor to finding the eigenvalues analytically. We just want the general location of the spectrum and a decent approximation. That is why I wrote serviceability as a NFR. 
Also to test this NFR I made two tests, one that checks to see if the matrix is the correct form (ie the top right quadrant is diagonal etc... ) and one that checks the eigenvalues versus other software. I am now thinking that these tests are more appropriate for reliability (ie how reliable are the eigen-values, how reliable is my code in making the matrix with the correct form). But this does not change the fact that the eigen-values aren't necessarily good quality or that the code is working at high performance. 
I feel like these tests are very necessary as my code revolves heavily around this matrix. 
So should I change my NFR from serviceable to reliable, or is there another word that is better? 

Robert

PS: sorry I am noticing this post-SRS. I started writing my test cases and realized that I might actually want a different NFR, I am not sure though.

**Comment by smiths** [comment]
@whitere123, I'm glad you thinking about these things.  It will definitely improve the quality of your documentation and code.  😄 

I don't really use the word serviceability.  It is a serviceable word, pun intended, but it isn't really necessary.  The word reliability can get the job done for you.  Having an NFR about reliability doesn't actually mean you are aiming for reliable software.  The purpose of the NFR is to state what level of reliability you want.  That is the NFR is your target for reliability.  It is completely fine to aim for output where reliability isn't that important.

Having said the above, what you are really talking about is accuracy.  I don't think you really want software that isn't reliable in terms of meeting its requirements.  What you are saying is that you need answers that are close enough, and that is about accuracy.  You don't have to be on the true answer, you can be reasonably close to it.

I haven't reviewed your SRS yet, but my guess is that what you want is an NFR related to accuracy.

**Comment by whitere123** [comment]
Alright, thank you for your feedback. 

Also, do you have a usb to hdmi cable I can borrow for the presentation tomorrow? I want to go through the current draft of my sysVnVplan, but I do not have the proper cable for the surfacebook pro laptop.

**Comment by smiths** [comment]
@whitere123, no I do not have a usb to hdmi cable.  The projector in our room uses VGA, so you need a connector that can transform what you have to VGA.  If you need it, you can use my laptop.

**Comment by whitere123** [comment]
I will most likely need your laptop for my presentation. I plan on displaying my requirements and systemVnVplan on the projector.

**Comment by smiths** [comment]
Okay
