### ISSUE TITLE
References in sysVnVplan ?

### ISSUE THREAD

**Issue by whitere123** [whitere123/CAS741_REW#12]
Hello Dr. Smith, 

What is the difference between "references" in section 3 and "references" section 6 of the sysVnVplan template? 

Best wishes. 
Robert

**Comment by smiths** [comment]
Good question.  I can see why that would be confusing.  Section 3 is the related documentation for your project, while the References at the end of the report is a summary of any cited literature.  To make this a little more clear, I'll rename Section 3 to Relevant Documentation.

**Comment by whitere123** [comment]
Thank you for your message. 
Also when is the systVnVPlan due? Is it 11:59PM today? or 11:59PM tomorrow?

**Comment by smiths** [comment]
The due date is Monday, Oct 22 by 11:59 pm.  I'm pretty sure that is unambiguous.  😄

**Comment by whitere123** [comment]
Is it alright if I have a 24 hour extension for the SystVnVPlan? (ie oct 23 by 11:59PM)

**Comment by smiths** [comment]
Yes.

**Comment by whitere123** [comment]
I am still learning about one of my test cases with my thesis supervisor. Is it alright if I mention it in my SystVnVPlan but do not include a data table with specific input and output? My other test cases have this data table, so my entire test plan isn't nonspecific..

**Comment by smiths** [comment]
@whitere123, yes this is fine.  Please make sure you include a comment in your document where the future details will be added.
