### ISSUE TITLE
System Verification and Validation Submission 

### ISSUE THREAD

**Issue by whitere123** [whitere123/CAS741_REW#13]
Hello Dr. Smith, 

I have completed my SystVnVPlan, its in my repository. It is ready for your review and grading. 

Best wishes, 
Robert 

PS: Thank you for the extension.

**Comment by smiths** [comment]
My comments on the System VnV plan can be found in 5fc2368.

**Comment by whitere123** [comment]
Ok, thank you @smiths, I have read your comments . Will we receive our grades soon on avenue?

**Comment by smiths** [comment]
@whitere123, the grades will come after I've completed the review for everyone.  I hope to have everything graded by early next week.
