### ISSUE TITLE
Recommendations for the latex bibliography

### ISSUE THREAD

**Issue by PeaWagon** [whitere123/CAS741_REW#14]
Here is my suggestion for how to do the bibliography. Right now, you are manually typing all of your references in text (and all of your bibtex entry names are the same).

Step 1: generate references for your items in bibtex format. 
Step 2: add these entries to a bib file (I've been using References.bib). Then you can reference it in your tex document as so: \bibliography {../../../ReferenceMaterial/References}. 
Step 3: in the text, use \cite{bib-entry-name}. 

See this webpage for examples on bibtex entries: [https://verbosus.com/bibtex-style-examples.html](url)

**Comment by whitere123** [comment]
Yes, I also have to make this change in my SRS. 
You also made me realize that my code compiles with a lot of warnings when I do not comment out "\usepackage[round]{natbib}" .  When I comment out this line everything compiles without warning messages (as I am not doing my references properly).

I will keep this issue open as I have to fix the referencing format in all of my latex files (even SRS). 

@smiths is it alright if for my SRS I re-upload a tex file with \usepackage[round]{natbib} commented out. The copy I submitted compiles and produces the right pdf.. I just had a lot of warning messages. If I comment out that line everything compiles with no warning. I am worried that it may have not compiled on your end as it compiled on my end with some "warnings".

**Comment by smiths** [comment]
@whitere123,  your problem is using the enumitem package and the natbib package together.  I haven't looked into the details, but there is some kind of conflict.   Yes, commenting out the natbib package should address the problem.

**Comment by whitere123** [comment]
Yes, I was being sloppy with the bibliography in all of my documents. This is all fixed. 
Thank you @PeaWagon and @smiths
