### ISSUE TITLE
Referencing section numbers and tables in latex

### ISSUE THREAD

**Issue by PeaWagon** [whitere123/CAS741_REW#15]
- you should use \label{label-name} to label your section headers. Then, in the document you can just reference label via \ref{label-name}. That way, if you add a section, the label auto-updates the number (and in some cases the label becomes clickable). I'm mostly referring to your references to the appendix section.
- same note as above except for table labels. You may need to create a table environment (and sometimes it will give you a question mark (?) in the text if you don't put the label after the table contents - not really sure. Latex is weird).

**Comment by whitere123** [comment]
Alright I added the labels. Thank you for this suggestion!
