### ISSUE TITLE
Additional suggestions

### ISSUE THREAD

**Issue by PeaWagon** [whitere123/CAS741_REW#16]
Add a linter as a static verification technique. Those things are awesome for ensuring that your code looks nice. Essentially, linters go through the code and make sure you have consistent spacing, capitalisation etc. What are you writing your code in? Maybe look for a linter specific to your programming language.

In the usability survey, may want to ask what other software solves the user's problem (or other software that they tried to use to solve their problem), so you can look at that software for ideas on how to improve your project (keep track of the competition, worth a check).

Not sure if this was a good idea or not, but for my tests I wrote a description saying why they were necessary and/or what they were trying to prove/test. You have referenced the SRS and those requirements, but maybe a brief statement for each test would help the reader to follow what each test is doing. Even just elaborating on the short forms for the test names would be helpful. If this is not what Prof. Smith has in mind, please ignore this comment.

Maybe you can give a specific measure such that you know your code is maintainable. Like for instance asking a lab member to edit a function (or add to a function) and seeing how easy it is for them to make the change. If you are importing external libraries, how often do you expect those libraries to update (i.e. how often will you be required to run your tests and ensure nothing has broken due to an external update?).

**Comment by whitere123** [comment]
- Thank you for telling me about linters. I will definitely add that. 
- I already ask "How does this program compare with other software that finds this particular spectrum?" and I think that is enough.  
- I may not include more details in the test descriptions as it is clear from the traceability and name of each test what each test is testing. 
- The maintainablility is just for my supervisor. So i think it is enough to just have his approval. 

Thank you for your suggestions I will close this issue soon.
