### ISSUE TITLE
Some nitpicky things for VnV plan

### ISSUE THREAD

**Issue by PeaWagon** [whitere123/CAS741_REW#17]
**Typesetting comments:**
- put the accent for Schrödinger (\" (umlaut or dieresis): \"{o}) in section 3.1 - introduction
- the same goes for my vnv plan - do we have to put the "list of figures" section if we don't have any figures? It looks awkward when it's empty.
- use ` to indicate left quotations in section 7.3 for the 'V' and for test-Rcon1 (and some other places)
- there is a small discussion about making tables without vertical lines. At least in some of your tables they might look cleaner without the vertical bars (|). [https://tex.stackexchange.com/questions/40542/why-not-use-vertical-lines-in-a-tabular](url) Just try it and see.
- the title for your document should have SpecSearch in it, not "Project Title:..."

**Comment by whitere123** [comment]
I think I will remove the list of figures entirely as it adds an empty page to my document. 
I also made the other necessary changes (except for the vertical bars, these table formats were taken from the latex templates).  
I will close this issue soon.

**Comment by smiths** [comment]
@PeaWagon, I noticed a question about whether "list of figures" has to be included when there are no figures.  No,  you can comment it out if there are no figures.  If you wanted to leave the heading and have the content of the section list "Not applicable" that would also be fine.
