### ISSUE TITLE
MG Hierarchy and control

### ISSUE THREAD

**Issue by whitere123** [whitere123/CAS741_REW#19]
Hello Dr. Smith @smiths , 

I was wondering if you could give me some feedback on my hierarchy table and maybe explain briefly what a control module is. 

Best wishes , 
Robert

**Comment by smiths** [comment]
Hello Robert.  You might want to combine your Input Parameters and Input Format modules.  The Numerical Parameters module is storing constants, right?  If the values in this module are the same from one program run to the next, then this module makes sense.  If the values change for every run, then these values could probably go to the Input Parameters module.

The control module is the module that coordinates the interaction between all of the modules.  It is like your main.c program in a C program.

**Comment by whitere123** [comment]
Thank you for your comments. I have made the changes and will submit my MG soon.
