### ISSUE TITLE
SRS edit

### ISSUE THREAD

**Issue by whitere123** [whitere123/CAS741_REW#2]
Hello Dr. Smith, 

I have completed a draft of my SRS. I added my comments and concerns in red (don't worry there are no comments in the Contents).

**Comment by whitere123** [comment]
I was wondering if you could read it over. You had mentioned last class that you would be willing to edit our SRS documents. 

Best wishes, 
Robert

**Comment by smiths** [comment]
I replied to some of your comments in b2c97f6.

**Comment by smiths** [comment]
I've completed addressing your comments in ab06adb.
