### ISSUE TITLE
MG typos, inconsistencies, other minor formatting issues

### ISSUE THREAD

**Issue by bmaclach** [whitere123/CAS741_REW#21]
The following is a list of minor issues I found with the MG:

- Many acronyms are used without first defining them in the text (ex. AC, UC, M). They should be defined the first time they are used. I would also advocate for a table of acronyms in the front of the document, though this would be a change in the template so let's see what @smiths thinks.
- Use of the word "Module" in module names should be consistent. In Section 4 some modules include the word "Module" and some do not, whereas in section 6 every module includes the word "Module". I think it's safe to remove the word "Module" from all the module names based on discussion during class presentations
- In the module hierarchy table in Section 4, there is a typo. "Ellipitic" should be "Elliptic"
- In the first paragraph of Section 6, the last sentence, "Also indicate if the module will be implemented specifically for the software", does not make sense (image below for context). This is from the template but I'm almost certain it's unintentional. It seems like it was supposed to be a comment. (Can you confirm, @smiths?)
![image](https://user-images.githubusercontent.com/18634568/48165435-94e72600-e2b3-11e8-88e4-bba4864c9e13.png)

- In section 6.2, for the Services of the behaviour-hiding module, the acronym SRS can be used without showing the full-form because the acronym was already defined in the Introduction section
- In section 6.2 and section 6.3, the Behaviour-Hiding module and Software Decision module are leaf modules, so they should be implemented by "-", not SpecSearch
- In section 6.2.4, a module called "Lambda Error Equation Module" is referenced but there is no such module
- Same for the "Domain Creation Module" in section 6.3.3 
- Same for the "operator matrix module" in sections 6.3.2 and 6.3.4
- Sections 6.2.5 and 6.2.6 reference other module names but do not capitalize the words in the names, whereas module names are capitalized when referenced elsewhere. To be consistent, always capitalize the module names
- Symbols should be italicized (_n_ in 6.3.1 and 6.3.2, _k_ in 6.3.3, and _dn_, _cn_, and _sn_ in 6.3.4)
- In section 6.3.6, there is a typo in the header. "Linpsace" should be "Linspace"
- In section 8, "directed acyclic graph" should be "Directed Acyclic Graph" since it is followed by the acronym
- In the uses hierarchy diagram, capitalization should be consistent (M4, M9, and M14 should have all words start with a capital)
- There is a typo in the uses hierarchy for M9. "Eigenvale" should be "Eigenvalue"
- The "M" labels in the uses hierarchy are mostly inconsistent with the rest of the document. It seems like they were all shifted up by 1 in the uses hierarchy, as Control Module changed from M14 to M3 (I think). I like the idea of changing the control module to M3 so that it is grouped with the other behaviour hiding modules, but this change should be propagated throughout the document.
- The word "Equations" is missing from the uses hierarchy for the "Spectrum Error Equations" module.
- "Eigen"  is missing before "vector" in M9 on the uses hierarchy

**Comment by whitere123** [comment]
Thank you for this thorough issue @bmaclach . So far I have made all of the changes that do not require @smiths approval. I will leave this issue open until we receive Dr. Smith's feedback regrading those two points.

**Comment by smiths** [comment]
Thank you for the detailed comments @bmaclach.  Very helpful!

Yes, a table of acronyms makes sense in the MG.  I'll add this to the blank project template.

@bmaclach is correct the text in the Module Decomposition section is incorrect.  I've updated this to something more reasonable in the blank project template.

**Comment by whitere123** [comment]
Thank you for your feedback @smiths and @bmaclach . 

All of the suggested changes in this issue have been made.
