### ISSUE TITLE
MG - Traceability between ACs and Modules

### ISSUE THREAD

**Issue by bmaclach** [whitere123/CAS741_REW#23]
I have a few comments about the traceability between anticipated changes and modules:

- In cases where 2 modules are impacted by a single AC (such as for AC4 and AC6), you should justify in the text why this design was chosen (probably in the paragraph at the beginning of section 8)
- Same for the case where a single module is associated with multiple ACs (such as M4)
- Based on design for change, every module should be associated with an AC. You should add some more ACs associated with the modules that aren't yet associated with an AC. You should be able to easily come up with these ACs based on the purpose of each module. As an example, an AC associated with the plotting module could be "The method used for plotting data". If you can't think of an AC for a module, that might be a sign that the module does not need to be separate and can instead be combined with a different module.

**Comment by whitere123** [comment]
Thank you. This was actually a very useful issue. I was able to come up with a lot more ACs because of your comments! I also modified pre-existing ACs.
