### ISSUE TITLE
MG - Traceability between modules and requirements

### ISSUE THREAD

**Issue by bmaclach** [whitere123/CAS741_REW#24]
It seems weird to me that some of your modules do not trace to any requirement. If the module does not help meet a requirement, why is it needed? I'm not sure if it was explicitly said that every module should trace to a requirement, but I think they should (correct me if I'm wrong @smiths)

M3, M5, M6, and M14 currently are not on the traceability matrix, but I think they can be added based on your existing requirements. For example, M3 (Output module) definitely contributes to the requirement for plotting the output, and M14 (Control module) probably contributes to all of the requirements. I am less sure about M5 and M6 but I suspect they also trace back to the existing requirements somehow, so these should all be added to the matrix.

**Comment by whitere123** [comment]
You are right. These modules are currently being added to the traceability. Thank you for this issue.

**Comment by smiths** [comment]
@bmaclach you are correct that every module should trace to a requirement.  I've read over your feedback to @whitere123 and I like what I'm seeing.  @whitere123, I also like your responses to @bmaclach.  These are exactly the kinds of exchanges I was hoping for between reviewer and reviewee.
