### ISSUE TITLE
MG - Issues with uses hierarchy

### ISSUE THREAD

**Issue by bmaclach** [whitere123/CAS741_REW#25]
I think the arrows in the uses hierarchy are backwards. A module should point to other modules that it uses. The input module is currently at the top of the hierarchy, which means that it uses many other modules, which seems wrong (Rather, many other modules probably use your inputs). Also, there is an arrow from Spectrum Matrix pointing to Eigenvalue and Eigenvector Solver, but in the text in section 6.2.3 it says that the Spectrum Matrix module is used by the Eigenvalue and Eigenvector Solver module, so the arrow should be pointing the opposite direction.

Also, the control module should use (probably many) other modules. The control module is the one that calls other modules to progress the running of the program. It should probably call the input module to get the inputs, pass those inputs to another module (potentially multiple other modules) to calculate your output, and then pass the output to the output module to return to the user.

One other issue is that the Hardware Hiding module is missing from the hierarchy. It should be used by your input and output modules.

**Comment by whitere123** [comment]
Yes, thank you for this issue. I figured this issue was on its way as I had a poor understanding of the hierarchy. I agree that I should reverse the arrows. But, do you think that I should also flip the entire hierarchy?

**Comment by bmaclach** [comment]
As long as the arrows point to the correct modules it is probably okay, but I do think it is best to have the arrows flow in a mostly downward direction (based on the feedback I got when presenting the hierarchy for my project), so that would mean flipping the entire hierarchy

**Comment by whitere123** [comment]
Alright I flipped everything. Thank you for your issues. Your issues really improved the quality of my MG.
