### ISSUE TITLE
Correct folder structure to match Blank Project Template

### ISSUE THREAD

**Issue by smiths** [whitere123/CAS741_REW#26]
Please modify the folder structure for your project to match the blank project template in the cas741 repo.  Standardizing on the same structure makes it easier to navigate your repo.  Also finding include files, like the Comments.tex file or the bib file, depend on a certain folder structure.

**Comment by whitere123** [comment]
Alright. I will address this issue by the end of the weekend. Sorry for the inconvenience.

**Comment by whitere123** [comment]
OK I modified everything.

**Comment by smiths** [comment]
Great!  In the future, please also include the hash code for the commit the closes the issue.  (The unique number that is given to every push.)  This lets you and others easily verify that the changes have been made.
