### ISSUE TITLE
Extension for UnitVnVPlan 

### ISSUE THREAD

**Issue by whitere123** [whitere123/CAS741_REW#29]
Hello @smiths , 

Would it be possible to submit my UnitVnVplan in the afternoon of Dec 5 (or even by midnight of Dec4)? 
I have an extremely busy week coming up. 

Best wishes, 
Robert

**Comment by smiths** [comment]
Hello @whitere123.  I do not normally extend deadlines this much in advance, but if it helps you feel less stress, we can agree now to a deadline extension to Dec 5 by 11:59 pm.

**Comment by whitere123** [comment]
It does, thank you. 
Also, will you be grading and providing feedback for the UnitVnVPlan before the dec 10 deadline ??

**Comment by smiths** [comment]
I will do my best to provided feedback.

**Comment by whitere123** [comment]
Alright, and one last question. 
What is the subtle difference between unit Vnv and System VnV. Should our unit VnVs be an extension of the system VnV or independent tests? 

Best wishes, 
Robert

**Comment by smiths** [comment]
@whitere123, I'm not sure the difference between the Unit VnV plan and the System VnV plan is that subtle.  😄  The System VnV plan is how you are going to verify the entire system.  It maps to the SRS.  It represents how you are going to verify that your system (software) meets the specification.  The Unit VnV plan describes how you are going to verify each of your modules individually.  (The system plan verifies them acting all together.)  The Unit VnV plan maps to your MIS.  It is how you will convince yourself that the code for each module correctly implements the specification given in the MIS.
