### ISSUE TITLE
SRS submission

### ISSUE THREAD

**Issue by whitere123** [whitere123/CAS741_REW#3]
Hello Dr. Smith, 

I have completed my SRS. 

Best wishes, 
Robert

**Comment by smiths** [comment]
Great!  I look forward to reviewing it.

**Comment by whitere123** [comment]
I made most (if not all) peer review edits for my SRS.

**Comment by smiths** [comment]
@whitere123, I have started reviewing your SRS.  Some initial comments are included in commit 1469743.

**Comment by whitere123** [comment]
Thank you @smiths . 

Are you expecting another edit of the SRS before all of the documentation is submitted at the end of the term? Or will you critique the SRS again at the end of the term with all the finalized changes?

**Comment by smiths** [comment]
@whitere123,  you can edit your document at any time, but I am only going to systematically review it twice: once now and once at the end of the term.  Of course, if you have any questions, do not hesitate to ask.  😄

**Comment by smiths** [comment]
@whitere123, I have completed my review of your SRS.  Comments are in 0facaea.

**Comment by whitere123** [comment]
Hello @smiths , 

I was wondering if there is a way to redeem myself for the SRS. I am slightly disappointed with my performance on the SRS. 

Best wishes, 
Robert

**Comment by smiths** [comment]
@whitere123, the SRS will be graded again when the final documentation is graded.  If you use/address the feedback I provided, then your grade on the final documentation will be the higher grade you are hoping for.  The final documentation contributes much more to your final grade than the stand-alone SRS grade.
