### ISSUE TITLE
Review MIS state variables

### ISSUE THREAD

**Issue by vajihehm** [whitere123/CAS741_REW#34]
@whitere123 Regarding to the template “all modules will have state variables. State variables give the module a memory”. In section 9 .4, 12.4, 14.4, 15.4, 16.4, 17.4, 18.4 should not there be state variables?

**Comment by whitere123** [comment]
Hello @vajihehm , 

Thank you for your comment. I do agree with you, however, from the PCM example there were some modules that did not have state variables. Also, these sections are discussing functions which simply take in a value and output a number. There is no sense of memory from my understanding. Maybe these functions should be associated to classes which actually have a memory, I am not too sure. Let me check with Dr. Smith. 
@smiths I think that I have a poor understanding of modules. Would you mind clarifying this issue^ 
For example, the eig() MATLAB function takes in an n by n matrix and outputs the eigenvalues and eigenvectors. Is there a sense of memory here? Would eig.val and eig.vect be the state variables or would there be no state variables? 

Robert

**Comment by smiths** [comment]
@whitere123 for the example you described (eig()) there would be no state variables. This is simply an input output relation.

**Comment by whitere123** [comment]
Alright, thank you for the clarification @smiths. I will close this issue as the other mentioned sections are similar to eig in that they involve only input output relation.
