### ISSUE TITLE
[SRS Review] Mathematical Notation 

### ISSUE THREAD

**Issue by hananezlitni** [whitere123/CAS741_REW#4]
Hello Robert,

I am posting my comments on your SRS.

**Section 2.4: Mathematical Notation** 

<img width="628" alt="screen shot 2018-10-10 at 11 16 41 pm" src="https://user-images.githubusercontent.com/22715360/46778626-93413700-cce2-11e8-862b-c9a9b00d4740.png">

The last definition (shown in the picture) does not seem to be very clear like the previous ones you wrote. Maybe you could explain what "e" represents? Another suggestion would be to add why the last formula equals to 1 (I believe because it's a Pythagorean identity formula, so you could write that to make it clearer).

**Comment by whitere123** [comment]
OK. I will add e to the list of symbols(it is a mathematical constant, Euler's number). I will also add the justification for the trig identity sin^2(x) + cos^2(x) = 1 in the reference material. 
Thanks for your feedback.
