### ISSUE TITLE
[SRS Review] System Constraints

### ISSUE THREAD

**Issue by hananezlitni** [whitere123/CAS741_REW#5]
**Section 4.3: System Constraints**

I'm not sure that what you wrote is actually your system's constraints. System constraints would be the things that the tool cannot be developed without, for example: a specific programming language. 

Therefore, unless your tool cannot operate or be developed without the current constraints (in that case it would probably be better to add explanation and state the reason why your tool needs those), I would probably move the first 2 sentences to "Assumptions" because they sound to me like assumptions more than constraints, and would omit the last sentence about MATLAB, because that's a design decision that shouldn't be included in the SRS.

**Comment by whitere123** [comment]
You are right, I will move the second sentence into assumptions and remove the first sentence (the first sentence is already in assumptions). 
As for the MATLAB part, I remember @smiths  saying in class that if your supervisor wants you to use a specific programming language than it should go into the constraints. Unless I am mixing this up with another section of the SRS.

**Comment by smiths** [comment]
@whitere123,  you are correct that if you are "required" to make a specific design decision, this should be classified as a constraint.  I suggest you add some external traceability information to your documentation to explicitly indicate that this constraint is imposed by your supervisor.

**Comment by whitere123** [comment]
What do you mean by "external traceability information" ?

**Comment by smiths** [comment]
We have internal traceability in our documents when we show how a theory is related to assumptions, for instance.  In this case, your supervisors requirement is not part of the existing documentation, but you still want traceability to his needs.  When you say the source of this constraint, you are providing this external traceability.

**Comment by whitere123** [comment]
OK. I will mention in the constraints that my supervisor wanted to work with matlab.
