### ISSUE TITLE
[SRS Review]  T, DD and IM Tables and their Derivations

### ISSUE THREAD

**Issue by hananezlitni** [whitere123/CAS741_REW#6]
**Section 5.2: Solution Characteristics Specification**

**For the derivations under the T, DD and IM tables:**

- In the first line of the derivation of DD1 (page 7 in the PDF file), I believe you mean "T1" instead of "T3"?

- It would be clearer if you add a subtitle at the beginning of each derivation, something like: "The Derivation of ..."

- The readability of the derivations could be enhanced using white spaces and text alignment, like the following screen shots from a previous project:

<div align="center">
<img width="500" src="https://user-images.githubusercontent.com/22715360/46780155-32692d00-cce9-11e8-9a44-4b75ede3c0f0.png">
 </div>

<br><br>

<div align="center">
<img width="500"  src="https://user-images.githubusercontent.com/22715360/46780160-34cb8700-cce9-11e8-92f0-822325c61cc7.png">
 </div>

**Comment by whitere123** [comment]
That is a good point. I will add a subtitle.  
Also, yes, that should be T1. In a previous draft I had T1 - T3. Nice catch!

**Comment by whitere123** [comment]
I also centered the equations in these new subsections. It makes it more readable. Thanks for the advice. 
@smiths is it ok if I add subsections between GDs, DDs and IMs that go over derivations?

**Comment by smiths** [comment]
The template already allows for additional information below any GD, DD or IM.  In the examples we have looked at this text is usually for providing a detailed derivation.  I don't think you want actual subsections that appear in the table of contents, but subsections, introduced with bold headings, that appear below a GD, or DD or IM are fine.

**Comment by hananezlitni** [comment]
@whitere123 you're welcome (:

**Comment by whitere123** [comment]
@smiths . Alright instead of making a new subsection I will make a bold and properly aligned title beneath the appropriate table.
