### ISSUE TITLE
[SRS Review] Traceability Tables and Graphs

### ISSUE THREAD

**Issue by hananezlitni** [whitere123/CAS741_REW#8]
**Section 8: Traceability Tables and Graphs**

In the PDF file, the traceability graph paragraph starts after the first table (end of page 10), and is cut by the second and third table and then continued. I checked the tex file and it was in the correct order, so there might be issues with the compiler.

**Comment by whitere123** [comment]
Yes , I am well aware of this. I do not know how to fix it.

**Comment by whitere123** [comment]
Update: I was able to get the tables in the correct order and the text about the graph to follow them. 
But, there is still a large amount of space between the tables and graph.. This issue is still open.

**Comment by hananezlitni** [comment]
I took a look at the tex file.. I think the reason there's a big gap after Table 3 is because page 14 is in landscape and the rest are portrait. I'm not sure about the gaps between the traceability graphs, but try setting a width and height for the graphs like you did in the system context figure.. it might omit the white space.
