### ISSUE TITLE
[SRS Review] Possible missing symbols in the table of symbols + a question

### ISSUE THREAD

**Issue by hananezlitni** [whitere123/CAS741_REW#9]
**Section 2.2: Table of Symbols**

The following are possible missing symbols in the table of symbols:

- “e” used in "Section 2.4: Mathematical Notation"

- “d” and “g” used in "IM1" table

- I believe that the “i” and “R (real number line)” symbols should be in the table of symbols instead of the table of acronyms and abbreviations 

**I have a question about the "u" symbol:** "u" is defined in the table of symbols as "wave amplitude". The same symbol is used in "Section 2.4: Mathematical Notation" as a complex number. Are they the same? If not, you might want to change the symbol used in Section 2.4 to avoid confusion.

**Comment by whitere123** [comment]
Yes, it would make sense to have these as symbols instead of abbreviations and acronyms. 
Also, I changed my definition of a complex number. The symbol u is used for something else, it was confusing.
